;; GENERATED by scripts/fetch_ech_configs.cljs — do not edit.
;;
;; ECHConfigList values as published in live HTTPS resource records
;; on 2026-08-27. Servers rotate ECH keys (draft-25 §4 recommends
;; daily), so re-running the script gives different bytes -- these
;; are a record of what was deployed, not a value to re-derive.
(ns tls.ech-configs)

(def fetched-on "2026-08-27")

(def live
  [{:host "crypto.cloudflare.com", :ech "AEX+DQBBbwAgACCcSqCCymWbpZSh2MukAi6EK9cGHbJNtMgI/KWdWVcZYAAEAAEAAQASY2xvdWRmbGFyZS1lY2guY29tAAA="}
   {:host "cloudflare-ech.com", :ech "AEX+DQBBbwAgACCcSqCCymWbpZSh2MukAi6EK9cGHbJNtMgI/KWdWVcZYAAEAAEAAQASY2xvdWRmbGFyZS1lY2guY29tAAA="}
   {:host "defo.ie", :ech "AMD+DQA8FAAgACC5d22Il/IsCEl0tKJrtthqoA6TI3hsZmcYmKuPBEq5TwAEAAEAAQANY292ZXIuZGVmby5pZQAA/g0APFIAIAAgEPJ+mSjH3/Dm9Vty24Kf/Vel4pAyvgl34is/GlPBu0EABAABAAEADWNvdmVyLmRlZm8uaWUAAP4NADxxACAAIFYctKxbePyiwuqoZzOHcacRu0gpiQmGsrm9JQtRreF0AAQAAQABAA1jb3Zlci5kZWZvLmllAAA="}])
