(ns tls.vectors
  "Access to the RFC 8448 fixture.

  The fixture is generated by `scripts/extract_rfc8448.cljs` from the RFC's own
  text and records the SHA-256 of the exact input it was derived from. Nothing
  in it was typed by hand.

  `blocks` is a flat, ordered vector, because that is what the RFC is: a
  transcript. Looking a value up by (actor, step, label) and *position* rather
  than by name alone matters -- `PRK` appears seventeen times, and a lookup
  that returned the first match would silently compare the wrong derivation
  and pass."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]))

(def fixture
  (delay (edn/read-string (slurp (io/resource "rfc8448_section3.edn")))))

(defn blocks [] (:rfc8448/blocks @fixture))

(defn find-all
  "Every block matching actor/step/label. `step` is matched as a substring so a
   test can name it the way the RFC does without quoting the punctuation."
  [{:keys [actor step label]}]
  (->> (blocks)
       (filter (fn [b]
                 (and (or (nil? actor) (= actor (:actor b)))
                      (or (nil? step) (and (:step b)
                                           (clojure.string/includes? (:step b) step)))
                      (or (nil? label) (= label (:label b))))))))

(defn one
  "Exactly one match, or throw. A vector lookup that silently picks among
   several is the same class of defect this whole suite exists to catch."
  [q]
  (let [ms (find-all q)]
    (case (count ms)
      1 (:bytes (first ms))
      0 (throw (ex-info "no RFC 8448 block matches" {:query q}))
      (throw (ex-info "ambiguous RFC 8448 lookup" {:query q :matches (count ms)})))))

(defn nth-of [q i] (:bytes (nth (find-all q) i)))
