#!/usr/bin/env nbb
;; Extract the labelled octet blocks of RFC 8448 into an EDN fixture.
;;
;; The vectors are NOT transcribed by hand. Every byte in
;; `test/tls13/vectors/rfc8448_section3.edn` comes out of this parser, run over
;; the RFC's own text, and the parser is self-checking: each block in the RFC
;; declares its own length ("(32 octets)"), and this refuses to emit a block
;; whose collected bytes do not reach exactly that count. A transcription slip
;; is therefore not a class of error that can reach the fixture -- either the
;; count matches or extraction fails loudly.
;;
;;   nbb scripts/extract_rfc8448.cljs <rfc8448.txt> <out.edn> [section-number]
;;
;; Provenance is written into the fixture: the source URL and the SHA-256 of
;; the exact input file, so a reader can re-fetch and re-derive.

(ns extract-rfc8448
  (:require ["node:fs" :as fs]
            ["node:crypto" :as crypto]
            [clojure.string :as str]))

(def source-url "https://www.rfc-editor.org/rfc/rfc8448.txt")

(defn hex-pairs
  "The 2-hex-digit tokens on a line, or nil if the line is not purely such
   tokens. Page furniture (the running header, 'Thomson  Informational
   [Page 4]', form feeds, blank lines) never matches, so it is skipped rather
   than silently absorbed as data."
  [line]
  (let [t (str/trim line)]
    (when (and (seq t) (re-matches #"(?:[0-9a-f]{2})(?: [0-9a-f]{2})*" t))
      (vec (str/split t #" ")))))

(defn block-start
  "-> {:label s :octets n :head tokens} for a line like
   '      key expanded (16 octets):  3f ce 51 60 ...', else nil."
  [line]
  (when-let [[_ label n tail] (re-find #"^\s{4,}([A-Za-z][A-Za-z0-9 _()-]*?)\s*\((\d+) octets?\):\s*(.*)$" line)]
    {:label (str/trim label)
     :octets (js/parseInt n 10)
     :head (or (hex-pairs tail) [])}))

(defn step-line
  "-> the '{client}  construct a ClientHello handshake message:' context."
  [line]
  (when-let [[_ actor text] (re-find #"^\s{3}\{(client|server)\}\s+(.*)$" line)]
    {:actor (keyword actor) :text (str/trim (str/replace text #":$" ""))}))

(defn collect
  "From line index `j`, gather hex tokens until exactly `octets` are in hand.
   Returns [tokens next-index]. Throws rather than returning a short block."
  [lines hi j octets head]
  (loop [j j, acc head]
    (cond
      (= (count acc) octets) [acc j]
      (> (count acc) octets) (throw (ex-info "overran declared octet count"
                                             {:declared octets :got (count acc) :line j}))
      (>= j hi) (throw (ex-info "input exhausted before declared octet count"
                                {:declared octets :got (count acc) :line j}))
      :else (if-let [p (hex-pairs (nth lines j))]
              (recur (inc j) (into acc p))
              (recur (inc j) acc)))))

(defn section-bounds [lines n]
  (let [head? (fn [k l] (re-matches (re-pattern (str "^" k "\\.\\s+\\S.*")) l))
        start (first (keep-indexed (fn [i l] (when (head? n l) i)) lines))
        _ (when-not start (throw (ex-info "section heading not found" {:section n})))
        end (first (keep-indexed (fn [i l] (when (and (> i start) (head? (inc n) l)) i)) lines))]
    [start (or end (count lines))]))

(defn extract [text n]
  (let [lines (vec (str/split-lines text))
        [lo hi] (section-bounds lines n)]
    (loop [i lo, step nil, out []]
      (if (>= i hi)
        out
        (let [line (nth lines i)]
          (if-let [s (step-line line)]
            (recur (inc i) s out)
            (if-let [{:keys [label octets head]} (block-start line)]
              (let [[toks j] (collect lines hi (inc i) octets head)]
                (recur j step (conj out {:actor (:actor step)
                                         :step (:text step)
                                         :label label
                                         :octets octets
                                         :bytes (mapv #(js/parseInt % 16) toks)})))
              (recur (inc i) step out))))))))

(defn -main [& args]
  (let [[in out sect] args
        n (js/parseInt (or sect "3") 10)
        text (str (fs/readFileSync in "utf8"))
        digest (-> (crypto/createHash "sha256") (.update text "utf8") (.digest "hex"))
        blocks (extract text n)]
    (when (zero? (count blocks))
      (println "extract: zero blocks -- refusing to write an empty fixture")
      (js/process.exit 2))
    (doseq [b blocks]
      (when-not (= (count (:bytes b)) (:octets b))
        (throw (ex-info "post-check failed" b))))
    (fs/writeFileSync
     out
     (str ";; GENERATED by scripts/extract_rfc8448.cljs -- do not edit by hand.\n"
          ";; Re-derive:  curl -sO " source-url "\n"
          ";;             nbb scripts/extract_rfc8448.cljs rfc8448.txt " out " " n "\n"
          (pr-str {:rfc8448/source source-url
                   :rfc8448/source-sha256 digest
                   :rfc8448/section n
                   :rfc8448/block-count (count blocks)
                   :rfc8448/blocks blocks})
          "\n"))
    (println (str "extract: section " n " -> " (count blocks) " blocks, "
                  (reduce + (map :octets blocks)) " octets, source sha256 " digest))))

(apply -main *command-line-args*)
