(ns fetch-ech-configs
  "Refresh `test/tls/ech_configs.cljc` from live HTTPS resource records.

  ECH configurations are published in DNS, in the `ech=` parameter of an
  HTTPS RR. This fetches a few over DNS-over-HTTPS and writes them out.

  ## This is a refresh, not a reproduction

  Servers rotate ECH keys — draft-25 §4 recommends daily — so re-running this
  produces **different bytes**, and that is correct rather than a fault. The
  fixture is not a value to be re-derived; it is a record that these exact
  bytes were being served by these hosts on the date in the header.

  So there is no sha256 pin here, unlike every other generator in this
  workspace. Pinning an input that is *designed* to change would make the
  script refuse every time it was right.

      nbb scripts/fetch_ech_configs.cljs 2026-08-27"
  (:require ["fs" :as fs]
            [clojure.string :as str]))

(def hosts ["crypto.cloudflare.com" "cloudflare-ech.com" "defo.ie"])

(defn- ech-param [data]
  (some->> (str/split data #"\s+")
           (keep #(when (str/starts-with? % "ech=") (subs % 4)))
           first))

(defn -main [& args]
  (let [date (or (first args) "unknown")]
    (-> (js/Promise.all
         (clj->js (map (fn [h]
                         (-> (js/fetch (str "https://cloudflare-dns.com/dns-query?name=" h "&type=HTTPS")
                                       #js {:headers #js {"accept" "application/dns-json"}})
                             (.then #(.json %))
                             (.then (fn [j]
                                      (let [d (js->clj j :keywordize-keys true)]
                                        {:host h
                                         :ech (some ech-param (map :data (:Answer d)))})))))
                       hosts)))
        (.then
         (fn [rs]
           (let [rs (filter :ech (js->clj rs :keywordize-keys true))]
             (when (empty? rs)
               (println "REFUSING: no host returned an ech= parameter")
               (js/process.exit 2))
             (doseq [r rs] (println (:host r) (count (:ech r)) "base64 chars"))
             (let [out (str ";; GENERATED by scripts/fetch_ech_configs.cljs — do not edit.\n;;\n"
                            ";; ECHConfigList values as published in live HTTPS resource records\n"
                            ";; on " date ". Servers rotate ECH keys (draft-25 §4 recommends\n"
                            ";; daily), so re-running the script gives different bytes -- these\n"
                            ";; are a record of what was deployed, not a value to re-derive.\n"
                            "(ns tls.ech-configs)\n\n"
                            "(def fetched-on " (pr-str date) ")\n\n"
                            "(def live\n  ["
                            (str/join "\n   " (map pr-str rs)) "])\n")]
               (fs/mkdirSync "test/tls" #js {:recursive true})
               (fs/writeFileSync "test/tls/ech_configs.cljc" out)
               (println "wrote test/tls/ech_configs.cljc" (count out) "bytes")))))
        (.catch (fn [e] (println "REFUSING:" (.-message e)) (js/process.exit 2))))))

(apply -main *command-line-args*)
